/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BookingController;
import View.*;
import java.awt.CardLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gandh
 */
public class AdminView extends javax.swing.JFrame {
            public String name;
            public String worker_id;
            DefaultTableModel requestHandleBookingsModel;
            DefaultTableModel paymentHandleBookingsModel;
            DefaultTableModel BookingsModel;
            
            private BookingController bookingController;
    /**
     * Creates new form HomeView
     */
    public AdminView(String[] credentials) {
        name=credentials[0];

        worker_id=credentials[1];
        initComponents();
        bookingController = new BookingController();
        initializeTables();
    }
    
    
    
    public void initializeTables(){
        BookingsModel = new DefaultTableModel();
        paymentHandleBookingsModel = new DefaultTableModel(){
            Class[] types = new Class [] {
               java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class,  java.lang.Object.class
            };
            
           boolean[] canEdit = new boolean [] {
                false,false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        requestHandleBookingsModel = new DefaultTableModel(){
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class
            };
            
           boolean[] canEdit = new boolean [] {
                false,false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
            int i=0;
            
        };
        BookingsModel.addColumn("User");
        BookingsModel.addColumn("Bill No");
        BookingsModel.addColumn("Room No");
        BookingsModel.addColumn("Room Type");
        BookingsModel.addColumn("Start Date");
        BookingsModel.addColumn("End Date");
        BookingsModel.addColumn("Amount");
        
        ResultSet BookingsModelResult = bookingController.getBookings();
        ResultSet[] unpaidBookingsModelResult_admin = bookingController.getUnpaidBookings_admin();
        
        try{
            while (BookingsModelResult.next()) {
                int user=BookingsModelResult.getInt("user");
                int BillNo = BookingsModelResult.getInt("bill_id");
                int roomNo = BookingsModelResult.getInt("room_no");
                String roomType = BookingsModelResult.getString("room_type");
                Date startDate = BookingsModelResult.getDate("start_date");
                Date endDate = BookingsModelResult.getDate("end_date");
                String totalAmount = BookingsModelResult.getString("Total_amount");

                // Add a row to the table model
                BookingsModel.addRow(new Object[]{user,BillNo, roomNo, roomType, startDate, endDate, totalAmount});
            }

            // Close result set and prepared statement
            BookingsModelResult.close();
       }catch(SQLException ex) {
            //model.addRow(new Object[]{null, null, "No data", null, null, null});
            // Handle exceptions
            ex.printStackTrace();
        }
        
        paymentHandleBookingsModel.addColumn("Type");
        paymentHandleBookingsModel.addColumn("Bill No");
        paymentHandleBookingsModel.addColumn("Generate Bill");
        paymentHandleBookingsModel.addColumn("Amount");
        
        
        jTable2.setModel(BookingsModel); // Set the model for jTable2
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);

        jButton1.setText("Handle Requests");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 170, 180, 70);

        
        jPanel1.add(jButton6);
        jButton6.setText("Accept Payments");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1070, 170, 180, 70);

        
        jTable2.setUpdateSelectionOnSort(false);
        jTable2.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.setRowHeight(60);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 300, 1470, 402);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Bookings");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(630, 250, 300, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Name    :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 30, 100, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText(name);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 30, 280, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText(worker_id);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 30, 140, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Customer ID    :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 30, 190, 40);

        getContentPane().add(jPanel1, "home");

        
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setText("Cancel Room");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(600, 10, 400, 80);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(10, 10, 50, 50);

        getContentPane().add(jPanel3, "Cancel Room");

        
        jPanel6.setLayout(null);

        jLabel6.setText("Accept Payments");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(600, 10, 400, 80);
        
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel2.setText("Book Room");
        //jPanel2.add(jLabel2);
        //jLabel2.setBounds(640, 10, 330, 80);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(10, 10, 50, 50);

        getContentPane().add(jPanel6, "Book Transportation");

        
        pack();
    }// </editor-fold>                        

                                         

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
                CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "Cancel Room");
    }                                     

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
                
    }                                    

                                         

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
                CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "Book Transportation");
    }                                     


    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
        
    }                                     

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
    }                                     

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
    }                                     

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
    }                                      

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
    }                                      

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "home");
    }                                      

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    
    // End of variables declaration                   
}
